import re

with open('templates/academy.html', 'r', encoding='utf-8') as f:
    html = f.read()

# 1. Update the dashboard-stats container to have the brain background and adjust the cards to be glassmorphic.
stats_section = r'''    <!-- ─── Profile & Stats Row ─── -->
    <div id="dashboard-stats" class="relative rounded-2xl overflow-hidden border border-[#1f2937] p-6 shadow-2xl">
        <!-- Dynamic Brain Background -->
        <div class="absolute inset-0 z-0 opacity-40 mix-blend-screen" style="background: url('/static/cyber_brain_bg.png') center/cover no-repeat; animation: pulse-bg 8s infinite alternate;"></div>
        <div class="absolute inset-0 bg-gradient-to-t from-[#0d1117] via-transparent to-transparent z-0"></div>
        
        <div class="relative z-10 grid grid-cols-1 md:grid-cols-4 gap-6">
            <!-- Profile Card -->
            <div class="md:col-span-1 bg-[#111827]/60 backdrop-blur-md border border-[#1f2937]/50 rounded-xl p-5 flex flex-col items-center gap-3 transition hover:border-emerald-500/30">
                <div class="w-20 h-20 rounded-full bg-gray-700 border-2 border-emerald-500 overflow-hidden relative group">
                    <img src="/static/hacker_avatar.png" class="w-full h-full object-cover transition duration-500 group-hover:scale-110" alt="Avatar" onerror="this.parentElement.innerHTML='<div class=\'w-full h-full bg-emerald-900 flex items-center justify-center text-3xl\'>🎭</div>'">
                    <div class="absolute inset-0 bg-emerald-500/20 opacity-0 group-hover:opacity-100 transition"></div>
                </div>
                <div class="text-center">
                    <div class="font-black text-white text-lg drop-shadow-md">Operator_X</div>
                    <div class="text-xs text-emerald-400 font-bold mono">🥇 Elite Hacker</div>
                </div>
                <div class="w-full">
                    <div class="flex justify-between text-xs mb-1"><span class="text-gray-400">Lv 42</span><span class="text-emerald-400 font-bold">3,400 / 5,000 XP</span></div>
                    <div class="xp-bar bg-black/50"><div class="xp-fill" style="width: 68%"></div></div>
                </div>
                <div class="grid grid-cols-3 w-full gap-2 mt-1 text-center text-xs">
                    <div class="bg-[#0d1117]/80 rounded-lg p-2 hover:bg-emerald-900/20 transition cursor-pointer"><div class="font-black text-white text-lg">47</div><div class="text-gray-500">Rooms</div></div>
                    <div class="bg-[#0d1117]/80 rounded-lg p-2 hover:bg-orange-900/20 transition cursor-pointer"><div class="font-black text-orange-400 text-lg">14</div><div class="text-gray-500">Streak</div></div>
                    <div class="bg-[#0d1117]/80 rounded-lg p-2 hover:bg-purple-900/20 transition cursor-pointer"><div class="font-black text-purple-400 text-lg">8</div><div class="text-gray-500">Badges</div></div>
                </div>
            </div>

            <!-- Streak Calendar -->
            <div class="md:col-span-1 bg-[#111827]/60 backdrop-blur-md border border-[#1f2937]/50 rounded-xl p-5 transition hover:border-orange-500/30">
                <div class="flex items-center gap-2 mb-4">
                    <span class="text-orange-400 text-lg animate-pulse">🔥</span>
                    <span class="font-black text-white drop-shadow-md">14-Day Streak</span>
                </div>
                <div class="grid grid-cols-7 gap-1.5 mb-3">
                    <div class="text-[9px] text-gray-400 text-center">M</div>
                    <div class="text-[9px] text-gray-400 text-center">T</div>
                    <div class="text-[9px] text-gray-400 text-center">W</div>
                    <div class="text-[9px] text-gray-400 text-center">T</div>
                    <div class="text-[9px] text-gray-400 text-center">F</div>
                    <div class="text-[9px] text-gray-400 text-center">S</div>
                    <div class="text-[9px] text-gray-400 text-center">S</div>
                </div>
                <div class="grid grid-cols-7 gap-1.5" id="streak-grid">
                    <!-- Generated by JS -->
                </div>
                <p class="text-[10px] text-gray-400 mt-3 text-center">Keep going! You're on fire 🔥</p>
            </div>

            <!-- Recent Badges -->
            <div class="md:col-span-1 bg-[#111827]/60 backdrop-blur-md border border-[#1f2937]/50 rounded-xl p-5 transition hover:border-blue-500/30">
                <div class="section-label mb-4 text-white">Recent Badges</div>
                <div class="grid grid-cols-4 gap-2">
                    <div class="flex flex-col items-center gap-1 group cursor-pointer" title="First Blood">
                        <div class="w-12 h-12 rounded-full bg-red-900/40 border border-red-500/30 flex items-center justify-center text-2xl transition group-hover:scale-110 group-hover:bg-red-500/20 group-hover:shadow-[0_0_15px_rgba(239,68,68,0.5)]">🩸</div>
                        <div class="text-[9px] text-gray-400 text-center group-hover:text-red-400 transition">First Blood</div>
                    </div>
                    <div class="flex flex-col items-center gap-1 group cursor-pointer" title="Web Hacker">
                        <div class="w-12 h-12 rounded-full bg-blue-900/40 border border-blue-500/30 flex items-center justify-center text-2xl transition group-hover:scale-110 group-hover:bg-blue-500/20 group-hover:shadow-[0_0_15px_rgba(59,130,246,0.5)]">🌐</div>
                        <div class="text-[9px] text-gray-400 text-center group-hover:text-blue-400 transition">Web Hacker</div>
                    </div>
                    <div class="flex flex-col items-center gap-1 group cursor-pointer" title="Networking">
                        <div class="w-12 h-12 rounded-full bg-emerald-900/40 border border-emerald-500/30 flex items-center justify-center text-2xl transition group-hover:scale-110 group-hover:bg-emerald-500/20 group-hover:shadow-[0_0_15px_rgba(16,185,129,0.5)]">🔌</div>
                        <div class="text-[9px] text-gray-400 text-center group-hover:text-emerald-400 transition">Networker</div>
                    </div>
                    <div class="flex flex-col items-center gap-1 group cursor-pointer" title="Linux Master">
                        <div class="w-12 h-12 rounded-full bg-orange-900/40 border border-orange-500/30 flex items-center justify-center text-2xl transition group-hover:scale-110 group-hover:bg-orange-500/20 group-hover:shadow-[0_0_15px_rgba(249,115,22,0.5)]">🐧</div>
                        <div class="text-[9px] text-gray-400 text-center group-hover:text-orange-400 transition">Linux Pro</div>
                    </div>
                    <div class="flex flex-col items-center gap-1 opacity-40 transition hover:opacity-100 cursor-pointer" title="Locked"><div class="w-12 h-12 rounded-full bg-black/50 border border-gray-700 flex items-center justify-center text-2xl">🔐</div><div class="text-[9px] text-gray-500 text-center">Locked</div></div>
                    <div class="flex flex-col items-center gap-1 opacity-40 transition hover:opacity-100 cursor-pointer" title="Locked"><div class="w-12 h-12 rounded-full bg-black/50 border border-gray-700 flex items-center justify-center text-2xl">🔐</div><div class="text-[9px] text-gray-500 text-center">Locked</div></div>
                    <div class="flex flex-col items-center gap-1 opacity-40 transition hover:opacity-100 cursor-pointer" title="Locked"><div class="w-12 h-12 rounded-full bg-black/50 border border-gray-700 flex items-center justify-center text-2xl">🔐</div><div class="text-[9px] text-gray-500 text-center">Locked</div></div>
                    <div class="flex flex-col items-center gap-1 opacity-40 transition hover:opacity-100 cursor-pointer" title="Locked"><div class="w-12 h-12 rounded-full bg-black/50 border border-gray-700 flex items-center justify-center text-2xl">🔐</div><div class="text-[9px] text-gray-500 text-center">Locked</div></div>
                </div>
            </div>

            <!-- Leaderboard snippet -->
            <div class="md:col-span-1 bg-[#111827]/60 backdrop-blur-md border border-[#1f2937]/50 rounded-xl p-5 transition hover:border-yellow-500/30 relative overflow-hidden">
                <div class="absolute -right-4 -top-4 w-16 h-16 bg-yellow-500/10 rounded-full blur-xl"></div>
                <div class="section-label mb-4 text-white">🏆 Live Leaderboard</div>
                <div class="space-y-3">
                    <div class="flex items-center gap-3 text-sm group">
                        <span class="text-yellow-400 font-black w-4 group-hover:scale-125 transition">1</span>
                        <div class="w-7 h-7 rounded-full bg-yellow-900/50 border border-yellow-500/30 flex items-center justify-center text-sm shadow-[0_0_10px_rgba(234,179,8,0.2)]">👑</div>
                        <span class="text-white font-bold flex-1">0xGh0st</span>
                        <span class="text-emerald-400 font-bold text-xs mono" id="lb-score-1">9,850 XP</span>
                    </div>
                    <div class="flex items-center gap-3 text-sm group">
                        <span class="text-gray-300 font-black w-4 group-hover:scale-125 transition">2</span>
                        <div class="w-7 h-7 rounded-full bg-gray-700 border border-gray-500/30 flex items-center justify-center text-sm">🦈</div>
                        <span class="text-white font-bold flex-1">d4rkn3t</span>
                        <span class="text-emerald-400 font-bold text-xs mono" id="lb-score-2">8,200 XP</span>
                    </div>
                    <div class="flex items-center gap-3 text-sm group">
                        <span class="text-orange-400 font-black w-4 group-hover:scale-125 transition">3</span>
                        <div class="w-7 h-7 rounded-full bg-orange-900/50 border border-orange-500/30 flex items-center justify-center text-sm">🐉</div>
                        <span class="text-white font-bold flex-1">r00tkit</span>
                        <span class="text-emerald-400 font-bold text-xs mono" id="lb-score-3">7,640 XP</span>
                    </div>
                    <div class="border-t border-[#1f2937]/50 my-2"></div>
                    <div class="flex items-center gap-3 text-sm bg-emerald-900/20 rounded-lg px-2 py-1.5 border border-emerald-500/30 shadow-[0_0_10px_rgba(16,185,129,0.1)] hover:bg-emerald-900/40 transition cursor-pointer">
                        <span class="text-emerald-400 font-black w-4">12</span>
                        <div class="w-7 h-7 rounded-full bg-emerald-900 border border-emerald-500/50 flex items-center justify-center text-sm">🎭</div>
                        <span class="text-emerald-300 font-bold flex-1">You</span>
                        <span class="text-emerald-400 font-bold text-xs mono">3,400 XP</span>
                    </div>
                </div>
            </div>
        </div>
    </div>'''

old_stats_pattern = re.compile(r'    <!-- ─── Profile & Stats Row ─── -->.*?</div>\s*</div>', re.DOTALL)
html = old_stats_pattern.sub(stats_section, html)

# 2. Add some CSS for the pulsing background
css = r'''
        @keyframes pulse-bg {
            0% { opacity: 0.3; filter: brightness(1); transform: scale(1); }
            100% { opacity: 0.55; filter: brightness(1.2); transform: scale(1.02); }
        }
'''
html = html.replace('</style>', css + '\n    </style>')

# 3. Add JS to make the leaderboard scores increase randomly (simulating live users)
js = r'''
// ═══════════════════════════════════════════════════════════
//  LIVE LEADERBOARD SIMULATION
// ═══════════════════════════════════════════════════════════
setInterval(() => {
    [1, 2, 3].forEach(id => {
        if (Math.random() > 0.7) {
            const el = document.getElementById('lb-score-' + id);
            if (el) {
                let current = parseInt(el.textContent.replace(/,/g, '').replace(' XP', ''));
                current += Math.floor(Math.random() * 15) * 10; // Add 0, 10, 20... 140 XP
                el.textContent = current.toLocaleString() + ' XP';
                
                // Add a flash effect
                el.style.color = '#fff';
                el.style.textShadow = '0 0 10px #10b981';
                setTimeout(() => {
                    el.style.color = '';
                    el.style.textShadow = '';
                }, 500);
            }
        }
    });
}, 3000);
'''
html = html.replace('</script>', js + '\n</script>')

with open('templates/academy.html', 'w', encoding='utf-8') as f:
    f.write(html)
